### ISSUE TITLE
Selected items seems faulty, start typing: Unhandled event loop exception

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#160]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. Select some elements. 
1. Right click: Selected items seems faulty (terminal choice) 
1. On the popup window, type the name of the method. 

**Expected results**
* Nothing unusuals happens. 

**Received results**
* Unhandled event loop exception, java.lang.IndexOutOfBoundsException: Index 50 out of bounds for length 50.

![unhandled_type](https://user-images.githubusercontent.com/16755484/89658310-afa65e80-d8ce-11ea-9978-ce9476e08dd2.jpg)

```
!ENTRY org.eclipse.ui 4 0 2020-08-07 16:51:45.572
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IndexOutOfBoundsException: Index 50 out of bounds for length 50
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.eclipse.sed.ifl.ide.gui.dialogs.CustomInputDialog.validateInputs(CustomInputDialog.java:150)
	at org.eclipse.sed.ifl.ide.gui.dialogs.CustomInputDialog.access$1(CustomInputDialog.java:146)
	at org.eclipse.sed.ifl.ide.gui.dialogs.CustomInputDialog$1.modifyText(CustomInputDialog.java:123)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:183)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
	at org.eclipse.swt.widgets.Text.wmCommandChild(Text.java:3014)
	at org.eclipse.swt.widgets.Control.WM_COMMAND(Control.java:4908)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4764)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:5831)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4820)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Text.callWindowProc(Text.java:313)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4858)
	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2618)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4812)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.sed.ifl.control.score.ScoreListControl.lambda$13(ScoreListControl.java:335)
	at org.eclipse.sed.ifl.util.event.core.ListenerCollection.invoke(ListenerCollection.java:33)
	at org.eclipse.sed.ifl.util.event.core.ListenerCollection.invoke(ListenerCollection.java:33)
	at org.eclipse.sed.ifl.ide.gui.ScoreListUI$7.widgetSelected(ScoreListUI.java:565)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
```

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs.2

**Comment by brita-sed** [comment]
The bug has been **corrected**.
