### ISSUE TITLE
[INVESTIGATION] In case of bigger projects Unhandled event loop exception, org.eclipse.swt.SWTError: No more handles error occurs

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#89]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a bigger project (joda-time). 
1. Click iFL button. 
1. Load scores. 
1. Select an item, then right click. 
1. Click Custom feedback... button. 
1. Made some action with methods, set different values etc. 

**Expected results**
* The plugin can handle bigger projects too. 

**Received results**
* Sometimes the following error I get, and Eclipse closes: 
```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.sed.ifl.ide.gui.element.ScoreSetter.createGlyph(ScoreSetter.java:110)
	at org.eclipse.sed.ifl.ide.gui.element.ScoreSetter.displayCurrentScoreDistribution(ScoreSetter.java:104)
	at org.eclipse.sed.ifl.view.ScoreSetterView.displayCurrentScoreDistribution(ScoreSetterView.java:60)
	at org.eclipse.sed.ifl.control.feedback.ScoreSetterControl.lambda$0(ScoreSetterControl.java:58)
	at org.eclipse.sed.ifl.util.event.core.ListenerCollection.invoke(ListenerCollection.java:33)
	at org.eclipse.sed.ifl.model.user.interaction.ScoreSetterModel.updateSubjects(ScoreSetterModel.java:45)
	at org.eclipse.sed.ifl.control.feedback.ScoreSetterControl.lambda$2(ScoreSetterControl.java:81)
	at org.eclipse.sed.ifl.util.event.core.ListenerCollection.invoke(ListenerCollection.java:33)
	at org.eclipse.sed.ifl.view.ScoreSetterView.lambda$0(ScoreSetterView.java:80)
	at org.eclipse.sed.ifl.util.event.core.ListenerCollection.invoke(ListenerCollection.java:33)
```

* Full log file: 
[unhandled_event_loop_log.txt](https://github.com/sed-szeged/iFL4Eclipse/files/4388836/unhandled_event_loop_log.txt)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
Retested on version https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.3. Result: another error occured: #169

This issue can be closed (because I cannot reproduce this bug).
